#ifndef CURVEPRESS_H
#define CURVEPRESS_H

/* Generated with cbindgen:0.27.0 */

/* AUTO-GENERATED by cbindgen — do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define cp_CP_OK 0

#define cp_CP_ERR_BAD_INPUT -1

#define cp_CP_ERR_BUFFER_TOO_SMALL -2

#define cp_CP_ERR_CORRUPT -3

#define cp_CP_ERR_PANIC -99

#define cp_CP_ERR_NULL -100

/**
 * Compression statistics (optional output from compress functions).
 */
typedef struct cp_CpStats {
    uintptr_t n_input;
    uintptr_t n_kept;
    uintptr_t bytes_raw;
    uintptr_t bytes_compressed;
    double ratio;
    double max_error;
    uint32_t quant_bits;
} cp_CpStats;

/**
 * Compress with RDP. `epsilon` is the maximum absolute error in the value domain.
 *
 * Pass `out_buf = NULL` for a dry run (writes required length to `*out_len`).
 * Returns 0 on success, negative error code otherwise.
 *
 * # Safety
 * All non-null pointers must be valid and properly aligned for their types.
 */

int32_t cp_compress_rdp(const int64_t *timestamps_ns,
                        const double *values,
                        uintptr_t n,
                        double epsilon,
                        uint8_t *out_buf,
                        uintptr_t out_cap,
                        uintptr_t *out_len,
                        struct cp_CpStats *stats)
;

/**
 * Compress with Visvalingam-Whyatt. `n_out` is the target number of kept points.
 *
 * # Safety
 * All non-null pointers must be valid and properly aligned for their types.
 */

int32_t cp_compress_vw(const int64_t *timestamps_ns,
                       const double *values,
                       uintptr_t n,
                       uintptr_t n_out,
                       uint8_t *out_buf,
                       uintptr_t out_cap,
                       uintptr_t *out_len,
                       struct cp_CpStats *stats)
;

/**
 * Compress with RDP-N (binary-searched epsilon to hit `n_out` points).
 * `epsilon` is the upper bound for the RDP search.
 *
 * # Safety
 * All non-null pointers must be valid and properly aligned for their types.
 */

int32_t cp_compress_rdpn(const int64_t *timestamps_ns,
                         const double *values,
                         uintptr_t n,
                         uintptr_t n_out,
                         double epsilon,
                         uint8_t *out_buf,
                         uintptr_t out_cap,
                         uintptr_t *out_len,
                         struct cp_CpStats *stats)
;

/**
 * Decompress a byte stream into `(ts_out, val_out)` arrays of capacity `n_cap`.
 *
 * Writes the number of decoded points to `*n_out`. Returns 0 on success.
 *
 * # Safety
 * All pointers must be valid. `ts_out` and `val_out` must have capacity `n_cap`.
 */

int32_t cp_decompress(const uint8_t *buf,
                      uintptr_t buf_len,
                      int64_t *ts_out,
                      double *val_out,
                      uintptr_t n_cap,
                      uintptr_t *n_out)
;

/**
 * Interpolate a single value at timestamp `t` from the support points.
 *
 * Writes the interpolated value to `*val_out`. Returns 0 on success.
 *
 * # Safety
 * All pointers must be valid.
 */

int32_t cp_interpolate(const int64_t *ts_in,
                       const double *val_in,
                       uintptr_t n_in,
                       int64_t t,
                       double *val_out)
;

/**
 * Return a static C string describing the error code.
 */
 const char *cp_strerror(int32_t err) ;

/**
 * Return the library version string (null-terminated).
 */
 const char *cp_version(void) ;

#endif  /* CURVEPRESS_H */
